### PR TITLE
Possible to configure table name

### LINKED ISSUE #10: Config TokensTable table
Default DB table for TokensTable table is `tokenize_tokens`, would it be wise to make it configurable? E.g.

```
Configure::write('Muffin/Tokenize', [
    'lifetime' => '3 days',
    'length' => 32,
   'table' => 'tokens',
]);
```

### PR DESCRIPTION
**Pull request by LubosRemplik**
Closes #10

### CODE REVIEW

**Comment by ADmad** [comment]
Please update readme to document that the table is configurable. 🙂

**Comment by LubosRemplik** [comment]
Updated ;-)

**Comment by ADmad** [comment]
1.1.0 released.

**Comment by LubosRemplik** [comment]
Thanks!

**Pull request merged**
