### PR TITLE
Possible to configure table name

### LINKED ISSUE #10: Config TokensTable table
Default DB table for TokensTable table is `tokenize_tokens`, would it be wise to make it configurable? E.g.

```
Configure::write('Muffin/Tokenize', [
    'lifetime' => '3 days',
    'length' => 32,
   'table' => 'tokens',
]);
```

### PR DESCRIPTION
**Pull request by LubosRemplik**
Closes #10

### CODE REVIEW

**Comment by LubosRemplik** [comment]
I have updated readme with latest changes (how to configure the plugin)

**Comment by LubosRemplik** [comment]
I can see we've both updated readme, ignore my second commit then

**Comment by ADmad** [comment]
You'll need to rebase your branch on top of upstream master and resolve the conflict so that your PR can be merged. :)

**Comment by LubosRemplik** [comment]
Sorry deleted branch by mistake, this is closed and another pull request #14 is opened without readme changes :)

**Pull request closed without merging**
